### PR TITLE
Fix NullPointerException when user has no tracks open

### LINKED ISSUE #586: NullPointerException when user do not have video / audio tracks open
Likely caused by commit a524c97c26a36a3761f6bdaf9fe5b3d27975e8a8 (PR #576).

By looking at the change, it removed null checks in original `createMediaStreamTracks` method:

```
public static MediaStreamTrackDesc[] createMediaStreamTracks(
        MediaStreamTrackReceiver mediaStreamTrackReceiver,
        List<SourcePacketExtension> sources,
        List<SourceGroupPacketExtension> sourceGroups)
{
    boolean hasSources = sources != null && !sources.isEmpty();
    boolean hasGroups = sourceGroups != null && !sourceGroups.isEmpty();
    if (!hasSources && !hasGroups)
    {
        return null;
    }
...
```

and refactored with:

```
public static MediaStreamTrackDesc[] createMediaStreamTracks(
        MediaStreamTrackReceiver mediaStreamTrackReceiver,
        List<SourcePacketExtension> sources,
        List<SourceGroupPacketExtension> sourceGroups)
{
    List<TrackSsrcs> trackSsrcsList = getTrackSsrcs(sources, sourceGroups);
...

private static List<TrackSsrcs> getTrackSsrcs(List<SourcePacketExtension> sources,
                                                  List<SourceGroupPacketExtension> sourceGroups)
    {
        //FIXME: determining the individual tracks should be done via msid,
        // but somewhere along the line we seem to lose the msid information
        // in the packet extensions
        List<TrackSsrcs> trackSsrcsList = new ArrayList<>();
        // We'll need to keep track of which sources and groups have been processed,
        // so make copies of the lists we've been given so we can modify them.
        List<SourcePacketExtension> sourcesCopy = new ArrayList<>(sources);
        List<SourceGroupPacketExtension> sourceGroupsCopy = new ArrayList<>(sourceGroups);
...
```

when `sources` or `sourceGroups` is null, exception is thrown.

```
video-bridge    | java.lang.NullPointerException
video-bridge    | 	at java.util.ArrayList.<init>(ArrayList.java:178)
video-bridge    | 	at org.jitsi.videobridge.xmpp.MediaStreamTrackFactory.getTrackSsrcs(MediaStreamTrackFactory.java:340)
video-bridge    | 	at org.jitsi.videobridge.xmpp.MediaStreamTrackFactory.createMediaStreamTracks(MediaStreamTrackFactory.java:394)
video-bridge    | 	at org.jitsi.videobridge.RtpChannel.setRtpEncodingParameters(RtpChannel.java:1919)
video-bridge    | 	at org.jitsi.videobridge.VideoChannel.setRtpEncodingParameters(VideoChannel.java:289)
video-bridge    | 	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:926)
video-bridge    | 	at org.jitsi.videobridge.Videobridge.handleColibriConferenceIQ(Videobridge.java:612)
video-bridge    | 	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQRequest(ComponentImpl.java:433)
video-bridge    | 	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:347)
video-bridge    | 	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQ(ComponentImpl.java:299)
video-bridge    | 	at org.jitsi.videobridge.xmpp.ComponentImpl.handleIQSetImpl(ComponentImpl.java:546)
video-bridge    | 	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362)
video-bridge    | 	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
video-bridge    | 	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
video-bridge    | 	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
video-bridge    | 	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
video-bridge    | 	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
video-bridge    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
video-bridge    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
video-bridge    | 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jiulongw**
Fixes #586

### CODE REVIEW

**Comment by jiulongw** [comment]
mvn test passed

**Comment by bgrozev** [comment]
Thanks for the contribution. Have you already signed the CLA?

Jenkins, ok to test

**Comment by jiulongw** [comment]
@bgrozev Just signed.  Thanks!

File: src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java [hunk 1]
```diff
@@ -245,21 +245,25 @@ else if (temporalIdx > 0)
     private static List<SecondarySsrc> getSecondarySsrcs(long ssrc, List<SourceGroupPacketExtension> sourceGroups)
     {
         List<SecondarySsrc> secondarySsrcs = new ArrayList<>();
-        for (SourceGroupPacketExtension sourceGroup : sourceGroups)
+        if (sourceGroups != null)
```
Comment (bbaldino) [inline src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java]: instead of nesting an `if` here, can we do an early return in the case where it's null?

Comment (bbaldino) [reply src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java]: also i think it may be better to fix this higher up the chain. in `org.jitsi.videobridge.RtpChannel.setRtpEncodingParameters(RtpChannel.java:1919)` we check for BOTH being empty or null, and if so return.  i think we should also check that if either is null, just replace it with an empty list.  then all the code in the calls from there can assume these are non-null (and would be even better to add a `@NotNull` annotation saying as such

Comment (jiulongw) [reply src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java]: Sounds good.  Updated.  I don't see anywhere else in this project using @NotNull (which I believe is not a standard JDK thing, only used by some IDE e.g. JetBrains), so I'll keep it as is.

**Comment by bbaldino** [comment]
beautiful, thanks.  i forgot i added the `@NonNull` annotations in libjitsi in some code i haven't merged yet, so yeah we can leave that off for now.  will merge once the tests look good.

File: src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java (hunk 1 above)
Comment (bgrozev) [reply src/main/java/org/jitsi/videobridge/xmpp/MediaStreamTrackFactory.java]: We started to use the jetbrains @NotNull annotation recently and it's only used in a couple of places so far.

**Comment by jiulongw** [comment]
Thanks!  Please squash these two commits as I didn't amend / force update this branch...
